-- pixel-swarm-basics.clawtest.lua
-- Basic sanity tests for Pixel Swarm RPG systems

describe("Game Services", function()
  it("workspace is accessible", function()
    expect(workspace):toBeNotNil()
  end)
  it("Players service exists", function()
    expect(Players):toBeNotNil()
  end)
  it("DataStoreService exists", function()
    local ds = game:GetService("DataStoreService")
    expect(ds):toBeNotNil()
  end)
  it("ReplicatedStorage exists", function()
    local rs = game:GetService("ReplicatedStorage")
    expect(rs):toBeNotNil()
  end)
end)

describe("Player Simulation", function()
  it("can add a player", function()
    Players:AddPlayer("TestHero")
    local p = Players:FindFirstChild("TestHero")
    expect(p):toBeNotNil()
  end)
  it("player has correct name", function()
    local players = Players:GetPlayers()
    local found = false
    for _, p in ipairs(players) do
      if p.Name == "TestHero" then found = true end
    end
    expect(found):toBeTruthy()
  end)
end)

describe("DataStore", function()
  it("can set and get values", function()
    local ds = game:GetService("DataStoreService"):GetDataStore("TestStore")
    ds:SetAsync("health", 100)
    local val = ds:GetAsync("health")
    expect(val):toBe(100)
  end)
  it("handles string values", function()
    local ds = game:GetService("DataStoreService"):GetDataStore("TestStore")
    ds:SetAsync("class", "Warrior")
    local val = ds:GetAsync("class")
    expect(val):toBe("Warrior")
  end)
end)

describe("Instance Creation", function()
  it("can create a Part", function()
    local p = Instance.new("Part")
    expect(p):toBeNotNil()
  end)
  it("part has correct ClassName", function()
    local p = Instance.new("Part")
    expect(p.ClassName):toBe("Part")
  end)
  it("part name is settable", function()
    local p = Instance.new("Part")
    p.Name = "TestBrick"
    expect(p.Name):toBe("TestBrick")
  end)
end)
